import json
from pathlib import Path


class ProjectGenerator:

    def __init__(self, workspace="generated_projects"):

        self.workspace = Path(workspace)

        self.workspace.mkdir(exist_ok=True)

    def generate(self, project_name):

        root = self.workspace / project_name

        folders = [

            "frontend",
            "frontend/public",
            "frontend/src",
            "frontend/src/components",
            "frontend/src/pages",
            "frontend/src/layouts",
            "frontend/src/hooks",
            "frontend/src/services",
            "frontend/src/assets",

            "backend",
            "backend/api",
            "backend/routes",
            "backend/controllers",
            "backend/models",
            "backend/services",
            "backend/utils",

            "database",

            "docs",

            ".github/workflows",

            ".hive",

        ]

        for folder in folders:

            (root / folder).mkdir(
                parents=True,
                exist_ok=True
            )

        files = {

            "README.md": f"# {project_name}\n\nGenerated by HIVE OS\n",

            ".gitignore":
"""node_modules
__pycache__
.env
dist
build
.vscode
.idea
*.pyc
*.log
coverage
""",

            "docker-compose.yml":
"""version: '3'

services:

  backend:

    build: ./backend

  frontend:

    build: ./frontend
""",

            "frontend/package.json":
"""{
  "name":"frontend",
  "private":true
}
""",

            "frontend/vite.config.js":
"""export default {};
""",

            "frontend/src/main.jsx":
"""import App from './App'

console.log('HIVE OS');
""",

            "frontend/src/App.jsx":
"""export default function App(){

  return <h1>HIVE Generated Project</h1>

}
""",

            "backend/requirements.txt":
"""fastapi
uvicorn
ollama
""",

            "backend/main.py":
"""from fastapi import FastAPI

app = FastAPI()

@app.get("/")

def home():

    return {"status":"running"}
""",

            "database/schema.sql":
"""-- Database Schema
""",

            ".hive/project.json":
json.dumps(
{
"name": project_name,
"version":"1.0"
},
indent=4,
),

            ".env.example":
"""ENV=development
PORT=8000
""",

            ".github/workflows/ci.yml":
"""name: CI
""",

            "LICENSE":
"""MIT License"""
        }

        for file, content in files.items():

            filepath = root / file

            filepath.parent.mkdir(
                parents=True,
                exist_ok=True
            )

            filepath.write_text(
                content,
                encoding="utf-8"
            )

        return str(root)