import { useEffect, useRef } from "react";
import MessageBubble from "./MessageBubble";

export default function ChatWindow({
  messages,
  research,
  engineer,
  designer,
  documentation,
  qa,
  leader,
}) {

  const scrollRef = useRef(null);

  useEffect(() => {

    if (scrollRef.current) {
      scrollRef.current.scrollTop =
        scrollRef.current.scrollHeight;
    }

  }, [
    messages,
    research,
    engineer,
    designer,
    documentation,
    qa,
    leader,
  ]);

  return (

    <div className="flex-1 min-h-0 flex flex-col bg-[#0B0F17] overflow-hidden">

      <div
        ref={scrollRef}
        className="flex-1 overflow-y-auto px-10 py-10"
      >

        <div className="max-w-5xl mx-auto">

          {messages.length === 0 && (

            <div className="min-h-[calc(100vh-320px)] flex flex-col justify-center items-center text-center px-8">

              <h1 className="text-4xl font-extrabold tracking-tight">

                HIVE OS

              </h1>

              <p className="mt-2 text-lg text-slate-300">

                Autonomous AI Software Engineering Workspace

              </p>

              <p className="mt-2 text-sm text-slate-500 max-w-xl">

                Research • Engineering • Design • Documentation • QA • Executive Review

              </p>

              <div className="mt-4 rounded-2xl border border-slate-700 bg-[#111827] p-4 text-left">

                <h3 className="text-lg font-semibold mb-4">

                  Try asking

                </h3>

                <ul className="space-y-2 text-sm text-slate-400">

                  <li>🚀 Build a modern SaaS dashboard</li>

                  <li>🛒 Create an ecommerce website</li>

                  <li>🤖 Build an AI chatbot</li>

                  <li>📱 Design a banking application</li>

                </ul>

              </div>

            </div>

          )}

          {messages.map((msg, index) => (

            <MessageBubble

              key={index}

              role={msg.role}

              text={msg.content}

            />

          ))}

          {(research ||

            engineer ||

            designer ||

            documentation ||

            qa ||

            leader) && (

            <div className="mt-10 rounded-3xl border border-slate-700 bg-[#111827] p-8">

              <h2 className="text-3xl font-bold mb-2">

                Mission Report

              </h2>

              <p className="text-slate-400 mb-8">

                Executive review generated by the HIVE AI organization.

              </p>

              {research && (

                <section className="mb-8 rounded-2xl border border-slate-700 bg-[#0B1220] p-6 hover:border-purple-500 transition-all duration-300 shadow-lg">

                  <h3 className="text-blue-400 text-xl font-bold mb-3">

                    🧠 Research

                  </h3>

                  <div className="bg-[#0F172A] rounded-2xl p-5 whitespace-pre-wrap">

                    {research}

                  </div>

                </section>

              )}

              {engineer && (

                <section className="mb-8 rounded-2xl border border-slate-700 bg-[#0B1220] p-6 hover:border-purple-500 transition-all duration-300 shadow-lg">

                  <h3 className="text-green-400 text-xl font-bold mb-3">

                    💻 Engineering

                  </h3>

                  <div className="bg-[#0F172A] rounded-2xl p-5 whitespace-pre-wrap">

                    {engineer}

                  </div>

                </section>

              )}

              {designer && (

                <section className="mb-8 rounded-2xl border border-slate-700 bg-[#0B1220] p-6 hover:border-purple-500 transition-all duration-300 shadow-lg">

                  <h3 className="text-pink-400 text-xl font-bold mb-3">

                    🎨 Design

                  </h3>

                  <div className="bg-[#0F172A] rounded-2xl p-5 whitespace-pre-wrap">

                    {designer}

                  </div>

                </section>

              )}

              {documentation && (

                <section className="mb-8 rounded-2xl border border-slate-700 bg-[#0B1220] p-6 hover:border-purple-500 transition-all duration-300 shadow-lg">

                  <h3 className="text-cyan-400 text-xl font-bold mb-3">

                    📄 Documentation

                  </h3>

                  <div className="bg-[#0F172A] rounded-2xl p-5 whitespace-pre-wrap">

                    {documentation}

                  </div>

                </section>

              )}

              {qa && (

                <section className="mb-8 rounded-2xl border border-slate-700 bg-[#0B1220] p-6 hover:border-purple-500 transition-all duration-300 shadow-lg">

                  <h3 className="text-violet-400 text-xl font-bold mb-3">

                    🧪 QA Review

                  </h3>

                  <div className="bg-[#0F172A] rounded-2xl p-5 whitespace-pre-wrap">

                    {qa}

                  </div>

                </section>

              )}

              {leader && (

                <section className="mb-8 rounded-2xl border border-slate-700 bg-[#0B1220] p-6 hover:border-purple-500 transition-all duration-300 shadow-lg">

                  <h3 className="text-yellow-400 text-2xl font-bold mb-3">

                    👑 Executive Summary

                  </h3>

                  <div className="bg-purple-900/20 border border-purple-500 rounded-2xl p-6 whitespace-pre-wrap leading-8">

                    {leader}

                  </div>

                </section>

              )}

            </div>

          )}

        </div>

      </div>

    </div>

  );

}